file(GLOB PROJECT_SOURCE_FILES CONFIGURE_DEPENDS
    "${PROJECT_INCLUDE_DIR}/shims/*.cpp"
    "${PROJECT_INCLUDE_DIR}/frontend/*.cpp"
    "${PROJECT_INCLUDE_DIR}/components/*.cpp"
    "${PROJECT_INCLUDE_DIR}/utilities/*.cpp"
    "${PROJECT_INCLUDE_DIR}/services/*.cpp"
	"${PROJECT_INCLUDE_DIR}/services/audio/*.cpp"
    "${PROJECT_INCLUDE_DIR}/services/video/*.cpp"
    "${PROJECT_INCLUDE_DIR}/systems/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/cores/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/cores/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/*.cpp"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/cores/*.cpp"
)

file(GLOB PROJECT_MODULE_FILES CONFIGURE_DEPENDS
    "${PROJECT_INCLUDE_DIR}/shims/*.cppm"
    "${PROJECT_INCLUDE_DIR}/frontend/*.cppm"
    "${PROJECT_INCLUDE_DIR}/components/*.cppm"
    "${PROJECT_INCLUDE_DIR}/utilities/*.cppm"
    "${PROJECT_INCLUDE_DIR}/services/*.cppm"
	"${PROJECT_INCLUDE_DIR}/services/audio/*.cppm"
    "${PROJECT_INCLUDE_DIR}/services/video/*.cppm"
    "${PROJECT_INCLUDE_DIR}/systems/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/cores/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/cores/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/*.cppm"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/cores/*.cppm"
)

file(GLOB PROJECT_HEADER_FILES CONFIGURE_DEPENDS
    "${PROJECT_INCLUDE_DIR}/shims/*.hpp"
    "${PROJECT_INCLUDE_DIR}/frontend/*.hpp"
    "${PROJECT_INCLUDE_DIR}/components/*.hpp"
    "${PROJECT_INCLUDE_DIR}/utilities/*.hpp"
    "${PROJECT_INCLUDE_DIR}/services/*.hpp"
    "${PROJECT_INCLUDE_DIR}/services/audio/*.hpp"
    "${PROJECT_INCLUDE_DIR}/services/video/*.hpp"
    "${PROJECT_INCLUDE_DIR}/systems/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/chip8/cores/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/bytepusher/cores/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/*.hpp"
	"${PROJECT_INCLUDE_DIR}/systems/gameboy/cores/*.hpp"
)
